### ISSUE TITLE
go.mod:3: invalid go version '1.22.2': must match format 1.23

### ISSUE THREAD

**Issue by Johnson90512** [dark-warlord14/CVENotifier#4]
Unable to install due to this error

**Comment by dark-warlord14** [comment]
Hi @Johnson90512 ,

Sorry for the delayed response. Haven't faced this error before, So I am not sure about the root cause.

Can you please share more information about below so I can try debugging this?
- What's the current go version you are using?
    - ```go version```
- Output of the installation command
    - ```go install github.com/dark-warlord14/CVENotifier/cmd/CVENotifier@latest``` 
- What is the OS that you are using?


Best,
@dark-warlord14

**Comment by Johnson90512** [comment]
Actually, I think the solution was to open go mod and get the EXACT version it stated then it installed! Thank you
